name: Block invalid PRs to main

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if source branch is not develop
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "‚ùå Solo se permiten PR desde 'develop' hacia 'main'"
            exit 1
          fi
        shell: bash